"""Tables our C# code looks words up in: English text the game passes as it is (a creature's species), or, later,
the English the Harmony patches catch. Their source is the game itself (sources.load builds them from the Base
folder), so they go through the usual catalog, store and translation, but the build writes them as C#
(mod/Grammar/CodeTables.g.cs, not in git: its keys are the game's English), not as a language file.

A catalog file is named Code.<Table>.example.xml; each entry is <entry Key="english" Text="▶english" />. A
translator's note «uk-voc: <form>» gives the vocative too (table <Table>.voc), for texts that address someone.
"""
from __future__ import annotations

import re
import xml.etree.ElementTree as ET

from .units import MARK

PREFIX = "Code."
SPECIES = "Code.Species.example.xml"
VOCATIVE = re.compile(r"^uk-voc:\s*(.+?)\s*$")


def is_code_table(name: str) -> bool:
    return name.startswith(PREFIX)


def table_name(name: str) -> str:
    """«Code.Species.example.xml» → «Species»."""
    return name[len(PREFIX):].removesuffix(".example.xml")


def table_xml(table: str, keys: list[str], build: str | None, source: str) -> str | None:
    if not keys:
        return None
    esc = lambda s: s.replace("&", "&amp;").replace('"', "&quot;").replace("<", "&lt;")
    body = "".join(f'  <entry Key="{esc(k)}" Text="{MARK}{esc(k)}" />\n' for k in keys)
    return ('<?xml version="1.0" encoding="utf-8"?>\n<!--\n'
            f"Caves of Qud - Generated Localizable XML {build or 'unknown'}\n"
            f"Not from the game: tools/qudtr/codetables.py builds it from {source}.\n\n"
            '<codetable Name="Key">\n\n  <entry Key="Key" Text="DisplayText">\n\n-->\n'
            f'<codetable Name="{table}" Lang="example" Encoding="utf-8">\n{body}</codetable>\n')


SPECIES_TAG = re.compile(r'<(?:tag|property)\s+Name="Species"\s+Value="([^"]+)"')
GENOTYPE_SPECIES = re.compile(r'<genotype\b[^>]*\bSpecies="([^"]+)"')


def species_xml(blueprints: dict[str, str], genotypes: str | None, build: str | None) -> str | None:
    """Every species the game can print through =x.species= / =x.apparentSpecies= (GameObject.GetSpecies: the
    Species property or tag; the genotypes' Species)."""
    keys = set()
    for text in blueprints.values():
        keys.update(SPECIES_TAG.findall(text))
    if genotypes:
        keys.update(GENOTYPE_SPECIES.findall(genotypes))
    keys = sorted(k for k in keys if re.search(r"[A-Za-z]", k))  # not the "*" wildcard
    return table_xml("Species", keys, build, "the Species tags of Base/ObjectBlueprints and Base/Genotypes.xml")


def entries(xml_text: str) -> list[str]:
    return [e.get("Key") for e in ET.fromstring(xml_text).iter("entry")]


def code_tables_cs(tables: dict[str, dict[str, str]]) -> str:
    """The C# that fills CodeTables (mod/Grammar/CodeTables.cs): table → English → Ukrainian."""
    def lit(s: str) -> str:
        return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'
    blocks = []
    for name, table in sorted(tables.items()):
        lines = "".join(f"                [{lit(k)}] = {lit(v)},\n" for k, v in sorted(table.items()))
        blocks.append(f"            t[{lit(name)}] = new Dictionary<string, string>\n            {{\n{lines}            }};\n")
    return ("// <auto-generated> by `py tools/qud.py build` from the Code.* catalogs. Not in git: the keys are the\n"
            "// game's English.\n"
            "using System.Collections.Generic;\n\n"
            "namespace CavesOfQudUA.Grammar\n{\n"
            "    public static partial class CodeTables\n    {\n"
            "        static partial void Fill(Dictionary<string, Dictionary<string, string>> t)\n        {\n"
            + "".join(blocks) + "        }\n    }\n}\n")
