"""Translation units of the official ExampleLanguage files, and building translated XML from them.

Every translatable thing in `ExampleLanguage/*.example.xml` is marked with '▶': an attribute
value, an element's text, or (in string tables) a `<string>` element. A unit's key is stable
across game builds as long as Freehold does not restructure the element it lives in:

* `<string Context="C" ID="I">` → msgctxt = C (absent when there is no Context), msgid = I
  (the ID *is* the English text and the game's lookup key, whitespace included).
* attribute → msgctxt = element path + "@" + attribute, e.g. `object[Snapjaw]/part[Render]@DisplayName`
* element text → msgctxt = element path, e.g. `topic[name=Quickstart]`

Element paths use each element's *key* attributes, read from the schema that the game writes
into the header comment of every example file (`<tag Name="Key" Value="DisplayText">`). Elements
without keys are positional; the 2nd, 3rd… sibling with the same segment gets '#2', '#3'….

A value with '▶' markers *inside* it is a compound value (alternatives separated by '~', keyed
lists such as `key|▶display,…`, `Faction::▶text`). Its msgid keeps every marker and the
translation must keep them in the same places; the build strips them.

A template (`<description>`, `<leveltext>`, `<template>` with child elements such as `<p>`,
`<stat/>`, `<statline/>`, `<switch>`) is one unit: its msgid is the inner XML with the markers
removed, and the translation is inner XML with the same tags. The game replaces the whole template
with the translated one (Templates.LoadTemplateFromExternal clears the old nodes).
"""
from __future__ import annotations

import collections
import dataclasses
import re
import xml.etree.ElementTree as ET

MARK = "▶"

# Used only for elements the file's schema does not describe (string tables and a few small
# files ship without one). Values that are ▶-marked never count as keys.
FALLBACK_KEYS = ("Name", "ID", "name", "Command", "Class", "Part", "Type", "Code")

# ▶-marked attributes that are really keys or English-only grammar switches. Translating them
# crashes the game or silently breaks grammar (see docs/research/official-framework.md), and the
# Ukrainian provider handles articles itself. They are restated in English when their element
# is written.
EXCLUDED_ATTRS = {
    ("xtagGrammar", "Proper"), ("xtagGrammar", "massNoun"), ("xtagGrammar", "adjunctNounPost"),
    ("xtagGrammar", "iArticle"),
    ("zone", "ProperName"), ("zone", "IndefiniteArticle"), ("zone", "DefiniteArticle"),
    ("part", "BaseHands"), ("part", "Category"),
    # a recipe category the player never sees; CyberneticsSchemasoft and DataDisk compare it
    # with English names written in the code
    ("mod", "TinkerCategory"),
}
EXCLUDED_VALUES = {"true", "false"}
# <tag|stag|property Name="X" Value="▶…">: values that are keys or English grammar, not text.
# The English article logic reads the articles (Translator.IndefiniteArticle); PronounSet names
# a pronoun set (GameObject.GetPropertyOrTag("PronounSet")); TinkerCategory is the recipe
# category above (TinkerItem); DisplayCharacter is the code of a bit type, looked up by the
# codes in recipes (BitType.FetchBitByCode).
EXCLUDED_TAG_NAMES = {"IndefiniteArticle", "DefiniteArticle", "PronounSet", "TinkerCategory",
                      "DisplayCharacter"}

# Roots whose loader merges attribute by attribute (verified: ObjectBlueprintXMLChildNode.Merge),
# so a translated file may contain just the translated attributes. Every other loader is treated
# as "the definition replaces the old one": BookUI, for one, clears a book's pages when the book is
# defined again, and naming lists carry Load="Replace".
SPARSE_ROOTS = {"objects"}

# Elements the game declares as LanguageXml.TemplateElement (2.0.212.31: MutationFactory
# description/leveltext, ActivatedAbilities description, Templates template). A test checks
# that no other ▶-marked element in the real files has child elements.
TEMPLATE_TAGS = frozenset({"description", "leveltext", "template"})
TEMPLATE_NOTE = ("XML template: translate the text and the DisplayName/Unit attributes; keep every "
                 "tag and its other attributes (Name, Value…) as they are. A <stat/> may move within "
                 "its sentence.")
# Inside a template (<p>, <stat/>, <statline/>, <switch>…) only these attributes are text.
TEMPLATE_TEXT_ATTRS = frozenset({"DisplayName", "Unit"})
MARKED_ATTR = re.compile('(=")' + MARK)

BUILD_RE = re.compile(r"\b(\d+\.\d+\.\d+\.\d+)\b")
SCHEMA_TAG = re.compile(r"<([A-Za-z_][\w.-]*)((?:\s+[\w:.-]+=\"[^\"]*\")*)\s*/?>")
SCHEMA_ATTR = re.compile(r"([\w:.-]+)=\"([^\"]*)\"")
GENERATED_MARKER = "Generated by tools/qud.py build"


@dataclasses.dataclass
class Unit:
    file: str                 # example file name, e.g. "Creatures.example.xml"
    msgctxt: str | None
    msgid: str
    kind: str                 # "string" | "attr" | "text" | "template"
    compound: bool = False
    note: str | None = None   # extracted comment for translators

    @property
    def key(self) -> tuple[str | None, str]:
        return (self.msgctxt, self.msgid)


# --------------------------------------------------------------------------------------------
# Small helpers

def base_name(example_name: str) -> str:
    """'Strings.Conversations.example.xml' -> 'Strings.Conversations'; 'HistorySpice.jsonc' -> 'HistorySpice'"""
    return example_name.removesuffix(".example.xml").removesuffix(".jsonc")


def is_spice(example_name: str) -> bool:
    return example_name.endswith(".jsonc")


def po_name(example_name: str) -> str:
    """'Strings.Conversations.example.xml' -> 'Strings.Conversations.po'"""
    return base_name(example_name) + ".po"


def output_name(example_name: str, lang: str = "uk") -> str:
    if is_spice(example_name):
        # HistoricSpice.Init merges mod files whose name starts with "historyspice."
        return f"{base_name(example_name).lower()}.{lang}.json"
    return base_name(example_name) + f".{lang}.xml"


def game_build(xml_text: str) -> str | None:
    """The build number from the generated header comment, e.g. '2.0.212.31'."""
    m = BUILD_RE.search(xml_text[:600])
    return m.group(1) if m else None


def unindent(text: str) -> str:
    """What the game does to XML text nodes (TextBuilder.Unindent): trim the whole text, then
    drop leading whitespace of every line, and remove carriage returns."""
    text = text.replace("\r", "").strip()
    return "\n".join(line.lstrip() for line in text.split("\n"))


def is_unit(value: str | None) -> bool:
    return value is not None and MARK in value


def is_compound(value: str) -> bool:
    """More than one marker, or a marker that is not at the start ('key,key,▶text')."""
    return value.count(MARK) > 1 or not value.startswith(MARK)


def strip_marks(value: str) -> str:
    return value.replace(MARK, "")


# syllables of the name generator: "true" there is a syllable of Templar Mecha names, not a boolean
NAME_PARTS = {"prefix", "infix", "postfix"}


def excluded(tag: str, attr: str, value: str, name: str | None = None) -> bool:
    boolean = strip_marks(value).strip() in EXCLUDED_VALUES and tag not in NAME_PARTS
    return ((tag, attr) in EXCLUDED_ATTRS or boolean
            or (tag in ("tag", "stag", "property") and attr == "Value" and name in EXCLUDED_TAG_NAMES))


def parse_schema(xml_text: str) -> dict[str, tuple[str, ...]]:
    """Key attributes per element tag, from the header comment the game generates."""
    m = re.search(r"<!--(.*?)-->", xml_text, re.S)
    schema: dict[str, list[str]] = {}
    if not m:
        return {}
    for tm in SCHEMA_TAG.finditer(m.group(1)):
        tag = tm.group(1)
        keys = schema.setdefault(tag, [])
        for am in SCHEMA_ATTR.finditer(tm.group(2)):
            if "Key" in am.group(2).split(",") and am.group(1) not in keys:
                keys.append(am.group(1))
    return {t: tuple(k) for t, k in schema.items()}


def _attr_msgid(value: str) -> tuple[str, bool]:
    compound = is_compound(value)
    return (value if compound else value[1:]), compound


def _text_msgid(text: str) -> tuple[str, bool]:
    t = unindent(text)
    compound = is_compound(t)
    if not compound:
        t = unindent(t[1:])
    return t, compound


def _has_text_unit(el: ET.Element) -> bool:
    return is_unit(el.text) and bool((el.text or "").strip())


def is_template(el: ET.Element) -> bool:
    """A ▶-marked template element with child elements: its inner XML is one unit."""
    return el.tag in TEMPLATE_TAGS and len(el) > 0 and is_unit(el.text)


def template_has_text(el: ET.Element) -> bool:
    """Whether a template holds anything to translate: text, or a DisplayName/Unit attribute.

    A template made only of tags (`<saveline Name=… Type=… />`) is no unit: there is nothing
    in it a translator could change."""
    return (bool(strip_marks("".join(el.itertext())).strip())
            or any(c.get(a) for c in el.iter() if c is not el for a in TEMPLATE_TEXT_ATTRS))


def inner_xml(el: ET.Element) -> str:
    """An element's content as XML text, markers removed, unindented like game text."""
    parts = [_esc_text(strip_marks(el.text or ""))]
    parts += [ET.tostring(child, encoding="unicode") for child in el]   # each with its tail
    return unindent(MARKED_ATTR.sub(r"\1", "".join(parts)))


def _compound_note(msgid: str) -> str:
    return ("Compound value: translate only the parts that follow each ▶, keep every ▶ and "
            "everything else (keys, separators) as is.")


def _esc_text(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _esc_attr(s: str) -> str:
    return (_esc_text(s).replace('"', "&quot;").replace("\n", "&#10;").replace("\t", "&#9;")
            .replace("\r", "&#13;"))


# --------------------------------------------------------------------------------------------
# One example file

class ExampleFile:
    def __init__(self, xml_text: str, name: str):
        self.text = xml_text
        self.name = name
        self.root = ET.fromstring(xml_text)
        self.schema = parse_schema(xml_text)
        self.build_number = game_build(xml_text)

    # ---- element identity

    def key_names(self, el: ET.Element) -> list[str]:
        names = self.schema.get(el.tag, FALLBACK_KEYS)
        return [a for a in names if el.get(a) is not None and not is_unit(el.get(a))]

    def segment(self, el: ET.Element) -> str:
        parts = [(a, el.get(a)) for a in self.key_names(el)]
        if not parts:
            return el.tag
        if len(parts) == 1 and parts[0][0] == "Name":
            return f"{el.tag}[{parts[0][1]}]"
        return el.tag + "[" + ",".join(f"{a}={v}" for a, v in parts) + "]"

    def child_segments(self, el: ET.Element):
        """Yield (child, segment) with a '#n' suffix for the 2nd+ sibling with the same segment."""
        seen: dict[str, int] = {}
        for child in el:
            if not isinstance(child.tag, str):
                continue  # comments / processing instructions
            seg = self.segment(child)
            seen[seg] = seen.get(seg, 0) + 1
            yield child, seg if seen[seg] == 1 else f"{seg}#{seen[seg]}"

    # ---- extraction

    def string_units(self, el: ET.Element) -> list[Unit]:
        ident = el.get("ID")
        value = el.get("Value")
        english = value if value is not None else unindent(el.text or "")
        if ident is None or not is_unit(english) or not strip_marks(english):
            return []
        compound = is_compound(english)
        # a compound string keeps its markers so the translator sees which parts are text
        msgid = english if compound else ident
        return [Unit(self.name, el.get("Context"), msgid, "string", compound,
                     _compound_note(msgid) if compound else None)]

    def units(self) -> list[Unit]:
        out: list[Unit] = []

        def walk(el: ET.Element, path: list[str]):
            if el.tag == "string":
                out.extend(self.string_units(el))
                return
            here = "/".join(path)
            for attr, value in el.attrib.items():
                if is_unit(value) and not excluded(el.tag, attr, value, el.get("Name")):
                    msgid, compound = _attr_msgid(value)
                    if strip_marks(msgid):   # "▶" alone: nothing to translate (" " is a real value)
                        # our own tables carry a Note attribute for the translator (codetables.py)
                        note = _compound_note(msgid) if compound else el.get("Note")
                        out.append(Unit(self.name, f"{here}@{attr}" if here else f"@{attr}", msgid, "attr",
                                        compound, note))
            if is_template(el) and path:
                if template_has_text(el):
                    out.append(Unit(self.name, here, inner_xml(el), "template", note=TEMPLATE_NOTE))
                return   # nothing inside a template is a unit of its own
            if _has_text_unit(el) and path:
                msgid, compound = _text_msgid(el.text)
                if strip_marks(msgid):
                    out.append(Unit(self.name, here, msgid, "text", compound,
                                    _compound_note(msgid) if compound else None))
            for child, seg in self.child_segments(el):
                walk(child, path + [seg])

        walk(self.root, [])
        return out

    # ---- building

    def build(self, translations: dict, lang: str = "uk", source_note: str = "") -> tuple[str | None, int]:
        """Return (xml, translated_count), or (None, 0) if nothing is translated.

        What gets written:
        * `<string>` entries: only translated ones (each is atomic).
        * `objects` files: only elements that contain a translation. An emitted element carries
          all of its own attributes, untranslated ones in English, so an element-level replace
          (as with xtags) cannot drop a grammar flag.
        * any other file: a top-level entry that contains a translation is written *complete*
          (every attribute, text and child, English where untranslated), because its loader
          may replace the whole definition.
        * positional siblings (two or more same-tag elements without a key, e.g. book pages or
          name syllables) are all-or-nothing, so positions and list lengths never change.
        Untranslated units that are not written fall back to English in the game.
        """
        sparse = self.root.tag in SPARSE_ROOTS

        def render_string(el, indent):
            us = self.string_units(el)
            if not us:
                return None
            t = translations.get(us[0].key)
            if t is None:
                return None
            if us[0].compound:
                t = strip_marks(t)
            attrs = [(k, v) for k, v in el.attrib.items() if k != "Value" and not is_unit(v)]
            attrs.append(("Value", t))
            return indent + "<string " + " ".join(f'{k}="{_esc_attr(v)}"' for k, v in attrs) + " />"

        def render(el, path, indent, complete):
            if el.tag == "string":
                return render_string(el, indent)
            here = "/".join(path)
            own = False
            attrs = []
            for attr, value in el.attrib.items():
                if not is_unit(value):
                    attrs.append((attr, value))
                    continue
                msgid, compound = _attr_msgid(value)
                t = None if excluded(el.tag, attr, value, el.get("Name")) else translations.get(
                    (f"{here}@{attr}" if here else f"@{attr}", msgid))
                if t is not None:
                    own = True
                    attrs.append((attr, strip_marks(t) if compound else t))
                else:
                    attrs.append((attr, strip_marks(value)))
            if is_template(el) and path:
                msgid = inner_xml(el)
                t = translations.get((here, msgid))
                if t is None and not complete:
                    return None
                attr_s = "".join(f' {k}="{_esc_attr(v)}"' for k, v in attrs)
                return f"{indent}<{el.tag}{attr_s}>{msgid if t is None else t}</{el.tag}>"
            text = None
            if _has_text_unit(el) and path:
                msgid, compound = _text_msgid(el.text)
                t = translations.get((here, msgid))
                if t is not None:
                    own = True
                    text = strip_marks(t) if compound else t
                else:
                    text = strip_marks(msgid)
            elif (el.text or "").strip() and complete:
                text = el.text.strip()
            children = render_children(el, path, indent + "  ", complete)
            if not (complete or own or children):
                return None
            attr_s = "".join(f' {k}="{_esc_attr(v)}"' for k, v in attrs)
            if not children and text is None:
                return f"{indent}<{el.tag}{attr_s} />"
            if not children:
                return f"{indent}<{el.tag}{attr_s}>{_esc_text(text)}</{el.tag}>"
            lead = _esc_text(text) if text is not None else ""
            return f"{indent}<{el.tag}{attr_s}>{lead}\n" + "\n".join(children) + f"\n{indent}</{el.tag}>"

        def render_children(el, path, indent, complete):
            items = list(self.child_segments(el))
            out = [render(c, path + [seg], indent, complete) for c, seg in items]
            if not complete:
                positional = collections.Counter(c.tag for c, _ in items if self.segment(c) == c.tag)
                for tag, n in positional.items():
                    idx = [i for i, (c, _) in enumerate(items) if c.tag == tag and self.segment(c) == c.tag]
                    if n >= 2 and any(out[i] is not None for i in idx):
                        for i in idx:
                            c, seg = items[i]
                            out[i] = render(c, path + [seg], indent, True)
            return [r for r in out if r is not None]

        children = []
        for child, seg in self.child_segments(self.root):
            r = render(child, [seg], "  ", False)
            if r is not None and not sparse and child.tag != "string":
                r = render(child, [seg], "  ", True)   # top-level entries are written complete
            if r is not None:
                children.append(r)
        count = len({u.key for u in self.units()} & translations.keys())
        if not count:
            return None, 0
        root_attrs = [("Lang", lang), ("Encoding", "utf-8")] + [
            (k, v) for k, v in self.root.attrib.items() if k not in ("Lang", "Encoding")]
        attr_s = "".join(f' {k}="{_esc_attr(v)}"' for k, v in root_attrs)
        header = (f"<!-- {GENERATED_MARKER} from translations/{lang}/{po_name(self.name)}. "
                  f"Do not edit. {source_note}").rstrip() + " -->"
        body = "\n".join(children)
        return (f'<?xml version="1.0" encoding="utf-8"?>\n{header}\n<{self.root.tag}{attr_s}>\n{body}\n'
                f'</{self.root.tag}>\n'), count

    # ---- reading an existing translated file back

    def read_translation(self, translated_xml: str, skip_identical: bool = True) -> dict:
        """Map units to the values found in a translated file of the same kind.

        The two trees are walked in parallel. A child of the translated file matches an
        example child when the tag and the example child's key attributes agree; among several
        such children (positional siblings like book pages) the n-th matches the n-th. Compound
        units are not read (their ▶ markers cannot be recovered). With `skip_identical`, values
        equal to the English text are ignored, since generated files restate English for
        untranslated units.
        """
        tr_root = ET.fromstring(translated_xml)
        found: dict = {}

        def keep(key, value, english):
            if not (skip_identical and value == english):
                found[key] = value

        if self.root.tag == "strings":
            table = {}
            for el in tr_root.iter("string"):
                value = el.get("Value")
                if value is None:
                    value = unindent(el.text or "")
                table[(el.get("Context"), el.get("ID"))] = value
            for u in self.units():
                if not u.compound and u.key in table:
                    keep(u.key, table[u.key], u.msgid)
            return found

        def walk(ex_el, tr_el, path):
            here = "/".join(path)
            for attr, value in ex_el.attrib.items():
                if is_unit(value) and not excluded(ex_el.tag, attr, value, ex_el.get("Name")):
                    msgid, compound = _attr_msgid(value)
                    if not compound and tr_el.get(attr) is not None:
                        keep((f"{here}@{attr}" if here else f"@{attr}", msgid), tr_el.get(attr), msgid)
            if is_template(ex_el) and path:
                msgid, value = inner_xml(ex_el), inner_xml(tr_el)
                if value:
                    keep((here, msgid), value, msgid)
                return
            if _has_text_unit(ex_el) and path and (tr_el.text or "").strip():
                msgid, compound = _text_msgid(ex_el.text)
                if not compound:
                    keep((here, msgid), unindent(tr_el.text), msgid)
            occurrence = collections.Counter()
            for child, seg in self.child_segments(ex_el):
                sig = (child.tag, tuple((a, child.get(a)) for a in self.key_names(child)))
                occurrence[sig] += 1
                candidates = [c for c in tr_el if c.tag == child.tag and all(c.get(a) == v for a, v in sig[1])]
                if len(candidates) >= occurrence[sig]:
                    walk(child, candidates[occurrence[sig] - 1], path + [seg])

        walk(self.root, tr_root, [])
        return found


# --------------------------------------------------------------------------------------------
# Function-style API

def extract(xml_text: str, name: str) -> list[Unit]:
    if is_spice(name):
        from . import spice
        return spice.extract(xml_text, name)
    return ExampleFile(xml_text, name).units()


def build(xml_text: str, name: str, translations: dict, lang: str = "uk",
          source_note: str = "") -> tuple[str | None, int]:
    if is_spice(name):
        from . import spice
        return spice.build(xml_text, name, translations, lang, source_note)
    return ExampleFile(xml_text, name).build(translations, lang, source_note)


def check_output(name: str, text: str) -> None:
    """Raises if a built file is not well-formed."""
    if is_spice(name):
        import json
        json.loads(text)
    else:
        ET.fromstring(text)
