"""List the game's =variable= replacer keys and which of them have a capitalized form.

Reads the decompiled Assembly-CSharp (work/decompiled/<build>/Assembly-CSharp) and writes
tools/qudtr/replacers.tsv, which the validator uses: a translation may capitalize a key
(=stat.statDisplayName= -> =stat.StatDisplayName=) only if the game registers that form.

Registration rules, from XRL.World.Text.Delegates.VariableReplacers.AddReplacer (2.0.212.31):
- keys are the attribute's Keys, or the method name with a lower-case first letter;
- with Capitalization = true every key is registered twice, lower- and upper-case first
  letter, the upper-case entry with Capitalize set (VariableObjectReplacer implies it);
- VariablePostProcessor keys go to a separate map (the part after '|').

Usage: py tools/analysis/replacers.py [DECOMPILED_ASSEMBLY_DIR]
"""
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
DEFAULT_SRC = REPO / "work" / "decompiled" / "2.0.212.31" / "Assembly-CSharp"
OUT = REPO / "tools" / "qudtr" / "replacers.tsv"

ATTR = re.compile(r"^\s*\[(VariableReplacer|VariableObjectReplacer|VariablePostProcessor)(?:\((.*)\))?\]\s*$")
METHOD = re.compile(r"\b(?:public|private|internal|protected)\s+static\s+[\w<>\[\],.?\s]+?\s+(\w+)\s*\(")
STRING = re.compile(r'"((?:[^"\\]|\\.)*)"')


def init_lower(s: str) -> str:
    return s[:1].lower() + s[1:]


def scan(src: pathlib.Path):
    rows = set()
    for path in sorted(src.rglob("*.cs")):
        lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
        pending = []
        for line in lines:
            m = ATTR.match(line)
            if m:
                kind, args = m.group(1), m.group(2) or ""
                # Keys are the string literals before any named argument (Default = "..." is not a key).
                positional = re.split(r"\b[A-Z]\w*\s*=", args, maxsplit=1)[0]
                keys = STRING.findall(positional)
                cap = kind == "VariableObjectReplacer" or re.search(r"\bCapitalization\s*=\s*true\b", args) is not None
                pending.append(("post" if kind == "VariablePostProcessor" else "replacer", keys, cap))
                continue
            if not pending:
                continue
            m = METHOD.search(line)
            if m:
                for kind, keys, cap in pending:
                    for key in keys or [init_lower(m.group(1))]:
                        rows.add((kind, init_lower(key) if cap else key, int(cap), f"{path.stem}.{m.group(1)}"))
                pending = []
            elif line.strip() and not line.strip().startswith(("[", "//", "///")):
                pending = []  # attribute on something other than a method
    return sorted(rows)


def main(argv):
    src = pathlib.Path(argv[1]) if len(argv) > 1 else DEFAULT_SRC
    if not src.is_dir():
        sys.exit(f"no decompiled code at {src}")
    rows = scan(src)
    header = ("# Generated by tools/analysis/replacers.py from the decompiled game code "
              f"({src.parent.name}). kind, key, capitalization (1 = an upper-case first letter "
              "is also registered), declaring method.\n")
    OUT.write_text(header + "".join("\t".join(map(str, r)) + "\n" for r in rows), encoding="utf-8", newline="\n")
    caps = sum(r[2] for r in rows)
    print(f"{len(rows)} keys ({caps} capitalizable) -> {OUT.relative_to(REPO)}")


if __name__ == "__main__":
    main(sys.argv)
